---
name: PlanAndApply

on:
  workflow_call:
    inputs:
      list_of_items:
        required: true
        type: string
jobs:
  demo:
  strategy:
    matrix:
      cluster: ${{ fromJSON( inputs.list_of_items ) }}
  steps:
    - name: demo
      runs: |
        echo ${{ matrix.cluster }}
