---
name: PlanAndApply

on:
  workflow_call:
    inputs:
      list_of_items:
        required: true
        type: string
jobs:
  demo:
    strategy:
      matrix:
        cluster: ${{ fromJSON( inputs.list_of_items ) }}
        # cluster: ["x", "y"]
    steps:
      - name: demo
        run: |
          echo "Testing"
