---
name: PlanAndApply

on:
  workflow_call:
    inputs:
      cluster_env:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 1
        run: |
          echo ${{ inputs.cluster_env }}
  apply:
    runs-on: ubuntu-latest
    needs: [plan]
    steps:
      - name: Echo 2
        run: |
          echo ${{ inputs.cluster_env }}
