# This is a basic workflow to help you get started with Actions

name: FeatureBranch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_env: ["a", "b"]
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo ${{ matrix.cluster_env }}
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            cluster_env:
              - 'env/${{ matrix.cluster_env }}.yaml'
